/*
 * Copyright 2017-2022 Product Mog LLC, 2022-2026 Revetware LLC.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * This generated source contains data derived from Unicode CLDR 48.2. CLDR data files are
 * Copyright © 1991-2026 Unicode, Inc. and licensed under Unicode License v3.
 * See THIRD-PARTY-NOTICES.md.
 */

package com.lokalized;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

// Generated by src/build/java/com/lokalized/cldr/CldrDataGenerator.java from CLDR 48.2. Do not edit by hand.
final class GeneratedCldrConformanceData {
  static final String CLDR_VERSION = "48.2";
  static final String SOURCE_URL = "https://github.com/unicode-org/cldr/tree/release-48-2/common/supplemental";
  static final String PLURALS_RESOURCE = "common/supplemental/plurals.xml";
  static final String ORDINALS_RESOURCE = "common/supplemental/ordinals.xml";
  static final String PLURAL_RANGES_RESOURCE = "common/supplemental/pluralRanges.xml";
  static final String PLURALS_SHA_256 = "d701d8b461afd2ba5eb21f9c1d645c8a661de225596afcf0f492ee36c69d727d";
  static final String ORDINALS_SHA_256 = "129bf4aa6f41d47931bf908ebaa261ec0b73b768f1fe3be90c06ab11fb49880a";
  static final String PLURAL_RANGES_SHA_256 = "42c82db9baaa8667921b4dea32b6322fd5e43004e166a43ae33b51cef5dc0f52";
  private static final List<CardinalitySample> CARDINALITY_SAMPLES = Collections.unmodifiableList(Arrays.asList(
      new CardinalitySample("he", "0.5", Cardinality.ONE),
      new CardinalitySample("he", "100", Cardinality.OTHER),
      new CardinalitySample("is", "0.1", Cardinality.ONE),
      new CardinalitySample("is", "0.2", Cardinality.OTHER),
      new CardinalitySample("mk", "11", Cardinality.OTHER),
      new CardinalitySample("mk", "21", Cardinality.ONE),
      new CardinalitySample("mt", "2", Cardinality.TWO),
      new CardinalitySample("mt", "20", Cardinality.OTHER),
      new CardinalitySample("fr", "1000000", Cardinality.MANY),
      new CardinalitySample("es", "1000000", Cardinality.MANY),
      new CardinalitySample("pt", "1000000", Cardinality.MANY),
      new CardinalitySample("ca", "1000000", Cardinality.MANY),
      new CardinalitySample("it", "1000000", Cardinality.MANY),
      new CardinalitySample("pt-PT", "0", Cardinality.OTHER),
      new CardinalitySample("pt-PT", "1", Cardinality.ONE),
      new CardinalitySample("pt-PT", "1000000", Cardinality.MANY)
  ));
  private static final List<OrdinalitySample> ORDINALITY_SAMPLES = Collections.unmodifiableList(Arrays.asList(
      new OrdinalitySample("en", "1", Ordinality.ONE),
      new OrdinalitySample("en", "2", Ordinality.TWO),
      new OrdinalitySample("en", "3", Ordinality.FEW),
      new OrdinalitySample("en", "4", Ordinality.OTHER),
      new OrdinalitySample("en", "11", Ordinality.OTHER),
      new OrdinalitySample("en", "12", Ordinality.OTHER),
      new OrdinalitySample("en", "13", Ordinality.OTHER),
      new OrdinalitySample("en", "21", Ordinality.ONE),
      new OrdinalitySample("it", "8", Ordinality.MANY),
      new OrdinalitySample("it", "11", Ordinality.MANY),
      new OrdinalitySample("it", "80", Ordinality.MANY),
      new OrdinalitySample("it", "800", Ordinality.MANY),
      new OrdinalitySample("it", "1", Ordinality.OTHER),
      new OrdinalitySample("cy", "0", Ordinality.ZERO),
      new OrdinalitySample("cy", "1", Ordinality.ONE),
      new OrdinalitySample("cy", "2", Ordinality.TWO),
      new OrdinalitySample("cy", "3", Ordinality.FEW),
      new OrdinalitySample("cy", "5", Ordinality.MANY),
      new OrdinalitySample("cy", "10", Ordinality.OTHER),
      new OrdinalitySample("as", "1", Ordinality.ONE),
      new OrdinalitySample("as", "2", Ordinality.TWO),
      new OrdinalitySample("as", "4", Ordinality.FEW),
      new OrdinalitySample("as", "6", Ordinality.MANY),
      new OrdinalitySample("as", "11", Ordinality.OTHER),
      new OrdinalitySample("gu", "1", Ordinality.ONE),
      new OrdinalitySample("gu", "2", Ordinality.TWO),
      new OrdinalitySample("gu", "4", Ordinality.FEW),
      new OrdinalitySample("gu", "6", Ordinality.MANY),
      new OrdinalitySample("gu", "5", Ordinality.OTHER),
      new OrdinalitySample("mk", "1", Ordinality.ONE),
      new OrdinalitySample("mk", "2", Ordinality.TWO),
      new OrdinalitySample("mk", "7", Ordinality.MANY),
      new OrdinalitySample("mk", "8", Ordinality.MANY),
      new OrdinalitySample("mk", "11", Ordinality.OTHER),
      new OrdinalitySample("mk", "12", Ordinality.OTHER),
      new OrdinalitySample("mk", "17", Ordinality.OTHER),
      new OrdinalitySample("mk", "18", Ordinality.OTHER),
      new OrdinalitySample("mk", "21", Ordinality.ONE),
      new OrdinalitySample("sv", "1", Ordinality.ONE),
      new OrdinalitySample("sv", "2", Ordinality.ONE),
      new OrdinalitySample("sv", "11", Ordinality.OTHER),
      new OrdinalitySample("sv", "12", Ordinality.OTHER),
      new OrdinalitySample("sv", "21", Ordinality.ONE),
      new OrdinalitySample("sv", "22", Ordinality.ONE),
      new OrdinalitySample("be", "2", Ordinality.FEW),
      new OrdinalitySample("be", "3", Ordinality.FEW),
      new OrdinalitySample("be", "12", Ordinality.OTHER),
      new OrdinalitySample("be", "13", Ordinality.OTHER),
      new OrdinalitySample("be", "22", Ordinality.FEW),
      new OrdinalitySample("az", "0", Ordinality.MANY),
      new OrdinalitySample("az", "1", Ordinality.ONE),
      new OrdinalitySample("az", "3", Ordinality.FEW),
      new OrdinalitySample("az", "6", Ordinality.MANY),
      new OrdinalitySample("az", "9", Ordinality.OTHER),
      new OrdinalitySample("tk", "6", Ordinality.FEW),
      new OrdinalitySample("tk", "10", Ordinality.FEW),
      new OrdinalitySample("gd", "11", Ordinality.ONE),
      new OrdinalitySample("or", "6", Ordinality.MANY),
      new OrdinalitySample("kw", "5", Ordinality.MANY)
  ));
  private static final List<CardinalityRangeSample> CARDINALITY_RANGE_SAMPLES = Collections.unmodifiableList(Arrays.asList(
      new CardinalityRangeSample("fa", Cardinality.OTHER, Cardinality.ONE, Cardinality.ONE),
      new CardinalityRangeSample("ak", Cardinality.OTHER, Cardinality.ONE, Cardinality.ONE),
      new CardinalityRangeSample("or", Cardinality.OTHER, Cardinality.ONE, Cardinality.ONE),
      new CardinalityRangeSample("as", Cardinality.ONE, Cardinality.ONE, Cardinality.ONE),
      new CardinalityRangeSample("ps", Cardinality.ONE, Cardinality.ONE, Cardinality.ONE),
      new CardinalityRangeSample("tk", Cardinality.OTHER, Cardinality.ONE, Cardinality.ONE)
  ));

  private GeneratedCldrConformanceData() {
    // Non-instantiable
  }

  static List<CardinalitySample> cardinalitySamples() {
    return CARDINALITY_SAMPLES;
  }

  static List<OrdinalitySample> ordinalitySamples() {
    return ORDINALITY_SAMPLES;
  }

  static List<CardinalityRangeSample> cardinalityRangeSamples() {
    return CARDINALITY_RANGE_SAMPLES;
  }

  static final class CardinalitySample {
    private final String cldrLocale;
    private final String sample;
    private final Cardinality expected;

    private CardinalitySample(String cldrLocale, String sample, Cardinality expected) {
      this.cldrLocale = cldrLocale;
      this.sample = sample;
      this.expected = expected;
    }

    String getCldrLocale() {
      return cldrLocale;
    }

    String getSample() {
      return sample;
    }

    Cardinality getExpected() {
      return expected;
    }
  }

  static final class OrdinalitySample {
    private final String cldrLocale;
    private final String sample;
    private final Ordinality expected;

    private OrdinalitySample(String cldrLocale, String sample, Ordinality expected) {
      this.cldrLocale = cldrLocale;
      this.sample = sample;
      this.expected = expected;
    }

    String getCldrLocale() {
      return cldrLocale;
    }

    String getSample() {
      return sample;
    }

    Ordinality getExpected() {
      return expected;
    }
  }

  static final class CardinalityRangeSample {
    private final String cldrLocale;
    private final Cardinality start;
    private final Cardinality end;
    private final Cardinality expected;

    private CardinalityRangeSample(String cldrLocale, Cardinality start, Cardinality end, Cardinality expected) {
      this.cldrLocale = cldrLocale;
      this.start = start;
      this.end = end;
      this.expected = expected;
    }

    String getCldrLocale() {
      return cldrLocale;
    }

    Cardinality getStart() {
      return start;
    }

    Cardinality getEnd() {
      return end;
    }

    Cardinality getExpected() {
      return expected;
    }
  }
}
